Aula1/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Aula1.Models
{
    public class Supplier
    {
        public long SupplierId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

Aula1/Controllers/SuppliersController.cs
using Aula1.Context;
using Aula1.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Aula1.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly EFContext _context = new EFContext();
        // GET: Suppliers
        public ActionResult Index()
        {
            return View(_context.Suppliers.OrderBy(s => s.Name));
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier supplier)
        {
            _context.Suppliers.Add(supplier);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }




        public ActionResult Edit(long? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var supplier = _context.Suppliers.Find(id.Value);

            if (supplier == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(supplier);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(supplier).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supplier);

        }




        public ActionResult Details(long? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Supplier supplier = _context.Suppliers.Where(s => s.SupplierId == id).Include("Products.Category").First();

            if (supplier == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(supplier);
        }





        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var supplier = _context.Suppliers.Find(id.Value);

            if (supplier == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(supplier);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Delete(long id)
        {

            Supplier supplier = _context.Suppliers.Find(id);
            _context.Suppliers.Remove(supplier);
            _context.SaveChanges();
            TempData["Message"] = "Supplier " + supplier.Name.ToUpper() + " foi removido";
            return RedirectToAction("Index");



        }



    }
}

Aula1/Views/Suppliers/Create.cshtml
@model	Aula1.Models.Supplier
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Registrando um novo Fabricante";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel	panel-primary">
        <div class="panel-heading">
            Registro um novo Fabricante
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="'form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer panel info">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit"
                       value="Adicionar Fabricante"
                       class="btn btn-danger" />
                @Html.ActionLink(
                 "Retornar para a listagem de Fabricantes",
                 "Index", null, new
                 {
                     @class =
                 "btn btn-warning"
                 })
            </div>
            <br />
            <br />
        </div>
    </div>
}

@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js">
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js">
    </script>
}

Aula1/Views/Suppliers/Delete.cshtml
@model Aula1.Models.Supplier

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Visualizando detalhes de fabricante a ser removido";
}

<h2>Visualizando detalhes de frabricante a ser removido</h2>

<div class="form-group">
    @Html.LabelFor(model => model.Name)
    <div class="input-group">
        <span class="input-group-addon">
            <i class="glyphicon	glyphicon-user"></i>
        </span>
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
</div>
<a href="#" class="btn btn-primary" data-toggle="modal"
   data-target="#deleteConfirmationModal">Remover</a>
@Html.ActionLink("Retornar	para a listagem", "Index", null, new { @class = "btn btn-success" })

<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-ELTEismiss
                        "modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Confirmação	de	exclusão de Categoria</h4>
            </div>
            <div class="modal-body">
                <p>
                    Você está prestes a remover o Fabricante @Model.Name.ToUpper() do cadastro.
                </p>
                <p>
                    <strong>
                        Você está certo	que	deseja	prosseguir?
                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "Suppliers", FormMethod.Post, new { @id = "delete-form", role = "form" }))
                {
                    @Html.HiddenFor(a => a.SupplierId)
                    @Html.AntiForgeryToken()
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" onclick="$('#delete-form').submit();">
                    Sim, exclua	este fabricante.
                </button>
                <button type="button" class="btn btn-primary"
                        data-dismiss="modal">
                    Não, não exclua	este fabricante.
                </button>
            </div>
        </div>
    </div>
</div>

@section ScriptPage	{
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liCategories').addClass("active");
        });
    </script>
}

Aula1/Views/Suppliers/Details.cshtml
@model Aula1.Models.Supplier

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Visualizando detalhes de um Fabricante";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Visualizando detalhes de um Fabricante
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            <br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            </div>
        </div>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Alterar", "Edit", new { id = Model.SupplierId }, new { @class = "btn btn-info" })
        @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-info" })
    </div>
</div>

@Html.Partial("~/Views/Products/_PorSupplier.cshtml", Model.Products.ToList())

@section	ScriptPage	{
    <script type="text/javascript">
	$(document).ready(function () {
    $('li').removeClass("active");
    $('#liProducts').addClass("active");});
    </script>
}

Aula1/Views/Suppliers/Edit.cshtml
@model Aula1.Models.Supplier

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Alterando os dados de um Fabricante";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Alteração dos dados de um Fabricante
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new
           {
               @class = "text-danger"
           })
                @Html.HiddenFor(model => model.SupplierId)
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="panel-footer panel-info">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit"
                           value="Gravar alterações"
                           class="btn btn-info" />
                    @Html.ActionLink(
                      "Retornar para a listagem de Fabricante",
                      "Index", null, new { @class = "btn btn-warning" })
                </div>
                <br />
                <br />
            </div>
        </div>
    </div>
}
@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js">
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js">
    </script>
}

Aula1/Views/Suppliers/Index.cshtml
@model IEnumerable<Aula1.Models.Supplier>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Lista de Fabricantes";
}

<div class="panel	panel-primary">
    <div class="panel-heading">
        Relação	de	Fabricantes	Registrados
    </div>
    <div class="panel-body">
        <table class="table	table-striped	table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.SupplierId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.SupplierId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.SupplierId })	|
                            @Html.ActionLink("Details", "Details", new { id = item.SupplierId })	|
                            @Html.ActionLink("Delete", "Delete", new { id = item.SupplierId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer	panel-info">
        @Html.ActionLink("Criar novo Fabricante", "Create", null, new { @class = "btn	btn-success" })
    </div>
</div>
@section	styles{<link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet" />}
@section	ScriptPage	{
    <script src=" @Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).ready(function () {
                $('li').removeClass("active");
                $('#liSuppliers').addClass("active");
                $('.table').dataTable({ "order": [[1, "asc"]] });
            });
    </script>
}